# Generated by Django 3.1.2 on 2020-11-03 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201101_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 3), null=True),
        ),
    ]
