# Generated by Django 3.1.2 on 2020-11-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201103_1116'),
        ('users', '0004_auto_20201103_1311'),
    ]

    operations = [
    ]
