# Generated by Django 3.1.2 on 2020-11-08 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20201103_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 8), help_text='ex: 2020-01-20', null=True),
        ),
    ]
