# Generated by Django 3.1.2 on 2020-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('1', 'Rock'), ('2', 'House'), ('3', 'Hip-Hop')], default=1, max_length=1),
        ),
    ]
